### ISSUE TITLE
If you don't supply PRIVATE_KEY_NAME and PUBLIC_KEY_NAME in .env node logs the error shown in comments.

### ISSUE THREAD

**Issue by tlhumphrey2** [hpcc-systems/Auth-Service#21]
{ Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at Object.<anonymous> (/app/routes/auth.js:23:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/app.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32) errno: -21, syscall: 'read', code: 'EISDIR' }

By the way, this happens even if you have disabled ssl in conf.d/nginx-conf.template

**Comment by ydahal1** [comment]
Private and public keys are used for signing and decoding tokens. Not for ssl. Since the whole purpose of auth service is to issue and validate tokens, private key and public keys are required  both with and without SSL
